name: unorm_dart
description: Unicode 8.0 Normalization - NFC, NFD, NFKC, NFKD
version: 0.1.0
homepage: https://github.com/yshrsmz/unorm-dart
author: Yasuhiro Shimizu <the.phantom.bane@gmail.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
